name: Emotes
main: me.superischroma.emotes.Emotes
version: 1.12
commands:
    emotes:
        description: Information about Emotes
        usage: /<command> [list]
    laugh:
        description: Laugh!
        usage: /<command> [player]
    raspberry:
        description: Blow a raspberry!
        usage: /<command> [player]
    dance:
        description: Do a dance!
        usage: /<command> [player]
    smile:
        description: Smile!
        usage: /<command> [player]
    cry:
        description: Cry.. cry away...
        usage: /<command> [player]
    grin:
        description: Smirkity smirk smirk!
        usage: /<command> [player]
    cheer:
        description: Cheeeer!
        usage: /<command> [player]
    backflip:
        description: Do a backflip!
        usage: /<command>
    greet:
        description: Greets everyone on the server!
        usage: /<command> [player]
    hug:
        description: Hug!
        usage: /<command> [player]
    kiss:
        description: Just a little smooch!
        usage: /<command> [player]
    highfive:
        description: Broosss!
        usage: /<command> [player]
    slap:
        description: Someone asleep? *SLAP*
        usage: /command [player]